// ── Static data — USMLE Step 1 only ───────────────────────────────────

export const STEP1_CATEGORIES = [
  "Behavioral Sciences", "Biochemistry & Nutrition", "Biostatistics & Epidemiology",
  "Cardiovascular", "Endocrine", "Gastrointestinal", "General Principles",
  "Hematology & Oncology", "Immune System", "Microbiology", "Musculoskeletal",
  "Nervous System", "Pathology", "Pharmacology", "Renal", "Reproductive", "Respiratory",
];

export const STEP1_PASSING_SCORE = 196;

export const RESOURCES = [
  { id: "firstaid", name: "First Aid", type: "learning", icon: "📕" },
  { id: "pathoma", name: "Pathoma", type: "learning", icon: "🔬" },
  { id: "sketchy", name: "Sketchy", type: "learning", icon: "🎨" },
  { id: "bnb", name: "Boards & Beyond", type: "learning", icon: "📺" },
  { id: "physeo", name: "Physeo", type: "learning", icon: "⚡" },
  { id: "pixorize", name: "Pixorize", type: "learning", icon: "🧩" },
  { id: "costanzo", name: "Costanzo Physiology", type: "learning", icon: "📘" },
  { id: "uworld", name: "UWorld", type: "practice", icon: "🎯" },
  { id: "amboss", name: "AMBOSS", type: "practice", icon: "💡" },
  { id: "anking", name: "AnKing Deck", type: "practice", icon: "🃏" },
];

export const HIGH_YIELD_WEIGHTS = {
  "Cardiovascular": 9, "Nervous System": 9, "Gastrointestinal": 8, "Renal": 8,
  "Respiratory": 7, "Pathology": 9, "Pharmacology": 9, "Biochemistry & Nutrition": 7,
  "Immune System": 7, "Microbiology": 7, "Endocrine": 7, "Hematology & Oncology": 7,
  "Reproductive": 6, "Musculoskeletal": 6, "Behavioral Sciences": 5,
  "General Principles": 5, "Biostatistics & Epidemiology": 4,
};

export const RESOURCE_MAP = {
  "Cardiovascular": { learning: ["firstaid", "bnb", "pathoma", "sketchy"], practice: ["uworld", "amboss", "anking"] },
  "Nervous System": { learning: ["firstaid", "bnb", "pathoma"], practice: ["uworld", "amboss", "anking"] },
  "Gastrointestinal": { learning: ["firstaid", "pathoma", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Renal": { learning: ["firstaid", "costanzo", "bnb", "pathoma"], practice: ["uworld", "amboss", "anking"] },
  "Respiratory": { learning: ["firstaid", "pathoma", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Pathology": { learning: ["pathoma", "firstaid", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Pharmacology": { learning: ["sketchy", "firstaid", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Biochemistry & Nutrition": { learning: ["pixorize", "firstaid", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Immune System": { learning: ["firstaid", "bnb", "pathoma"], practice: ["uworld", "amboss", "anking"] },
  "Microbiology": { learning: ["sketchy", "firstaid", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Endocrine": { learning: ["firstaid", "pathoma", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Hematology & Oncology": { learning: ["firstaid", "pathoma", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Reproductive": { learning: ["firstaid", "pathoma", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Musculoskeletal": { learning: ["firstaid", "pathoma", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Behavioral Sciences": { learning: ["firstaid", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "General Principles": { learning: ["firstaid", "bnb"], practice: ["uworld", "amboss", "anking"] },
  "Biostatistics & Epidemiology": { learning: ["firstaid", "bnb"], practice: ["uworld", "amboss"] },
};

export const SUB_TOPICS = {
  "Cardiovascular": [
    { topic: "Heart failure (systolic vs diastolic)", yield: 10 },
    { topic: "Valvular heart disease (murmurs, pathology)", yield: 10 },
    { topic: "Ischemic heart disease / MI (pathophys, ECG, enzymes)", yield: 10 },
    { topic: "Cardiac pharmacology (antiarrhythmics, antihypertensives)", yield: 9 },
    { topic: "Hypertension (primary, secondary causes)", yield: 9 },
    { topic: "Arrhythmias & ECG interpretation", yield: 9 },
    { topic: "Congenital heart defects (shunts, cyanotic vs acyanotic)", yield: 8 },
    { topic: "Shock (cardiogenic, hypovolemic, septic, neurogenic)", yield: 8 },
    { topic: "Atherosclerosis pathogenesis", yield: 7 },
    { topic: "Cardiac cycle & pressure-volume loops", yield: 7 },
    { topic: "Aortic dissection / aneurysm", yield: 6 },
    { topic: "Pericardial disease", yield: 5 },
    { topic: "Cardiac embryology (fetal circulation)", yield: 4 },
    { topic: "Cardiac tumors (myxoma)", yield: 3 },
  ],
  "Renal": [
    { topic: "Acid-base disorders (metabolic/respiratory, compensation, ABGs)", yield: 10 },
    { topic: "Electrolyte disorders (Na, K, Ca — causes & management)", yield: 10 },
    { topic: "Diuretics (mechanism, site of action, side effects)", yield: 9 },
    { topic: "Nephron physiology (filtration, reabsorption, secretion)", yield: 9 },
    { topic: "Glomerulonephritis / nephrotic vs nephritic syndrome", yield: 9 },
    { topic: "Acute kidney injury (pre-renal, intrinsic, post-renal)", yield: 8 },
    { topic: "RAAS system & blood pressure regulation", yield: 8 },
    { topic: "Chronic kidney disease (stages, complications)", yield: 7 },
    { topic: "Renal tubular acidosis (types I, II, IV)", yield: 7 },
    { topic: "Kidney stones (types, risk factors)", yield: 6 },
    { topic: "Polycystic kidney disease", yield: 5 },
    { topic: "Renal cell carcinoma", yield: 5 },
    { topic: "Renal embryology", yield: 3 },
    { topic: "Renal blood flow autoregulation", yield: 3 },
  ],
  "Nervous System": [
    { topic: "Stroke syndromes (vascular territories, deficits)", yield: 10 },
    { topic: "Neurotransmitters & receptor pharmacology", yield: 9 },
    { topic: "Cranial nerves (pathways, lesions, deficits)", yield: 9 },
    { topic: "Spinal cord lesions (Brown-Séquard, syringomyelia)", yield: 8 },
    { topic: "Seizure disorders & antiepileptic drugs", yield: 8 },
    { topic: "Demyelinating diseases (MS, Guillain-Barré)", yield: 8 },
    { topic: "Neurodegenerative diseases (Alzheimer's, Parkinson's, ALS)", yield: 8 },
    { topic: "Intracranial pressure / herniation syndromes", yield: 7 },
    { topic: "Brain tumors (types, location, age)", yield: 7 },
    { topic: "Meningitis (bacterial vs viral, CSF findings)", yield: 7 },
    { topic: "Headache syndromes (migraine, cluster, tension)", yield: 6 },
    { topic: "Peripheral neuropathies", yield: 6 },
    { topic: "Autonomic nervous system", yield: 6 },
    { topic: "Neural tube defects / CNS embryology", yield: 4 },
    { topic: "Sleep physiology", yield: 3 },
  ],
  "Gastrointestinal": [
    { topic: "Liver pathology (hepatitis, cirrhosis, liver failure)", yield: 10 },
    { topic: "GI pharmacology (PPIs, H2 blockers, anti-emetics)", yield: 9 },
    { topic: "Inflammatory bowel disease (Crohn's vs UC)", yield: 9 },
    { topic: "Peptic ulcer disease / H. pylori", yield: 8 },
    { topic: "GI cancers (colon, pancreatic, esophageal, gastric)", yield: 8 },
    { topic: "Pancreatic pathology (pancreatitis, pancreatic cancer)", yield: 8 },
    { topic: "Bilirubin metabolism & jaundice", yield: 8 },
    { topic: "Esophageal disorders (achalasia, Barrett's, varices)", yield: 7 },
    { topic: "Malabsorption syndromes (celiac, Whipple's)", yield: 7 },
    { topic: "Gallbladder disease (cholelithiasis, cholecystitis)", yield: 7 },
    { topic: "GI bleeding (upper vs lower, variceal)", yield: 7 },
    { topic: "Hernias (inguinal, femoral, hiatal)", yield: 6 },
    { topic: "Diarrhea (osmotic, secretory, infectious)", yield: 6 },
    { topic: "GI embryology (midgut rotation, atresias)", yield: 5 },
  ],
  "Pharmacology": [
    { topic: "Autonomic drugs (cholinergic, adrenergic, blockers)", yield: 10 },
    { topic: "Cardiac drugs (antiarrhythmics, antianginals, antihypertensives)", yield: 10 },
    { topic: "Antimicrobials (mechanism, resistance, side effects)", yield: 10 },
    { topic: "Drug metabolism & pharmacokinetics (CYP450, half-life, Vd)", yield: 9 },
    { topic: "Anti-inflammatory drugs (NSAIDs, corticosteroids)", yield: 8 },
    { topic: "Anticancer drugs (mechanism, side effects)", yield: 8 },
    { topic: "CNS drugs (antidepressants, antipsychotics, anxiolytics)", yield: 8 },
    { topic: "Anticoagulants & antiplatelets", yield: 8 },
    { topic: "Endocrine drugs (diabetes, thyroid, adrenal)", yield: 7 },
    { topic: "Lipid-lowering drugs (statins, fibrates)", yield: 7 },
    { topic: "Drug-drug interactions & adverse effects", yield: 7 },
    { topic: "Opioid pharmacology", yield: 6 },
    { topic: "Toxicology & antidotes", yield: 5 },
    { topic: "Immunosuppressants", yield: 5 },
  ],
  "Pathology": [
    { topic: "Inflammation (acute vs chronic, mediators)", yield: 10 },
    { topic: "Neoplasia (benign vs malignant, grading, staging, tumor markers)", yield: 10 },
    { topic: "Cell injury & death (apoptosis vs necrosis types)", yield: 9 },
    { topic: "Hemodynamics (thrombosis, embolism, infarction, edema)", yield: 9 },
    { topic: "Lab findings patterns (anemia workup, LFTs, etc.)", yield: 8 },
    { topic: "Wound healing & repair", yield: 7 },
    { topic: "Granulomatous diseases", yield: 7 },
    { topic: "Amyloidosis", yield: 6 },
  ],
  "Biochemistry & Nutrition": [
    { topic: "Metabolic pathways (glycolysis, TCA, ETC, gluconeogenesis)", yield: 9 },
    { topic: "Genetic disorders & inheritance patterns", yield: 9 },
    { topic: "Amino acid derivatives & metabolism disorders", yield: 8 },
    { topic: "Lysosomal storage diseases", yield: 8 },
    { topic: "Vitamins (deficiencies, toxicities)", yield: 8 },
    { topic: "Glycogen storage diseases", yield: 7 },
    { topic: "Lipid metabolism & transport (lipoproteins)", yield: 7 },
    { topic: "DNA replication, transcription, translation", yield: 7 },
    { topic: "DNA repair mechanisms", yield: 6 },
    { topic: "Collagen synthesis disorders", yield: 6 },
    { topic: "Purine & pyrimidine metabolism", yield: 5 },
    { topic: "Fatty acid oxidation disorders", yield: 5 },
  ],
  "Immune System": [
    { topic: "Hypersensitivity reactions (Types I–IV)", yield: 10 },
    { topic: "Immunodeficiency disorders (SCID, DiGeorge, Bruton's)", yield: 9 },
    { topic: "Autoimmune diseases (SLE, RA, Sjögren's)", yield: 9 },
    { topic: "Transplant rejection (hyperacute, acute, chronic)", yield: 8 },
    { topic: "T-cell and B-cell activation & differentiation", yield: 8 },
    { topic: "Complement system", yield: 7 },
    { topic: "Cytokines & their functions", yield: 7 },
    { topic: "MHC I vs MHC II", yield: 7 },
    { topic: "Vaccines & passive vs active immunity", yield: 5 },
    { topic: "Immune tolerance", yield: 4 },
  ],
  "Microbiology": [
    { topic: "Bacterial identification (Gram stain, culture, morphology)", yield: 10 },
    { topic: "Antimicrobial mechanisms & resistance", yield: 9 },
    { topic: "HIV / AIDS (pathogenesis, CD4, opportunistic infections)", yield: 9 },
    { topic: "Hepatitis viruses (A–E, serology)", yield: 9 },
    { topic: "Bacterial toxins & virulence factors", yield: 8 },
    { topic: "STIs (syphilis, chlamydia, gonorrhea, HPV, HSV)", yield: 8 },
    { topic: "Viral classification & replication", yield: 8 },
    { topic: "TB & atypical mycobacteria", yield: 7 },
    { topic: "Respiratory infections (pneumonia organisms by setting)", yield: 7 },
    { topic: "Fungal infections (Candida, Aspergillus, Crypto, Histo)", yield: 7 },
    { topic: "Parasitology (malaria, toxoplasma, giardia)", yield: 6 },
    { topic: "Prions", yield: 3 },
  ],
  "Endocrine": [
    { topic: "Diabetes mellitus (Type 1 vs 2, DKA vs HHS, insulin)", yield: 10 },
    { topic: "Thyroid disorders (hyper/hypo, Graves, Hashimoto's)", yield: 9 },
    { topic: "Adrenal disorders (Cushing's, Addison's, Conn's, pheo)", yield: 9 },
    { topic: "Pituitary disorders (prolactinoma, acromegaly, SIADH, DI)", yield: 8 },
    { topic: "Calcium & parathyroid disorders", yield: 8 },
    { topic: "Hypothalamic-pituitary axes", yield: 7 },
    { topic: "Adrenal steroid synthesis pathway", yield: 7 },
    { topic: "MEN syndromes", yield: 6 },
    { topic: "Pancreatic islet tumors (insulinoma, glucagonoma)", yield: 5 },
    { topic: "Carcinoid syndrome", yield: 4 },
  ],
  "Hematology & Oncology": [
    { topic: "Anemias (iron deficiency, B12/folate, sickle cell, thalassemia, hemolytic)", yield: 10 },
    { topic: "Coagulation cascade & bleeding disorders", yield: 9 },
    { topic: "Leukemias & lymphomas (ALL, AML, CLL, CML, Hodgkin's, NHL)", yield: 9 },
    { topic: "Blood smear findings & interpretation", yield: 8 },
    { topic: "Anticoagulants & antiplatelets (heparin, warfarin, DOACs)", yield: 8 },
    { topic: "Platelet disorders (ITP, TTP, HUS, DIC)", yield: 8 },
    { topic: "Tumor markers & paraneoplastic syndromes", yield: 7 },
    { topic: "Blood transfusion reactions", yield: 7 },
    { topic: "Myeloproliferative disorders", yield: 6 },
    { topic: "Plasma cell dyscrasias (multiple myeloma, Waldenström's)", yield: 6 },
  ],
  "Respiratory": [
    { topic: "Obstructive lung diseases (COPD, asthma, bronchiectasis)", yield: 10 },
    { topic: "Pulmonary embolism & DVT", yield: 9 },
    { topic: "Lung cancer (types, location, paraneoplastic)", yield: 8 },
    { topic: "Restrictive lung diseases (fibrosis, sarcoidosis)", yield: 8 },
    { topic: "Pneumonia (community, hospital, atypical organisms)", yield: 8 },
    { topic: "Pulmonary function tests (FEV1/FVC, compliance)", yield: 8 },
    { topic: "Pleural effusion (transudate vs exudate)", yield: 7 },
    { topic: "Oxygen-hemoglobin dissociation curve", yield: 7 },
    { topic: "TB (primary, secondary, PPD, treatment)", yield: 7 },
    { topic: "Respiratory pharmacology (bronchodilators, steroids)", yield: 7 },
    { topic: "Pneumothorax (tension, spontaneous)", yield: 6 },
    { topic: "ARDS & neonatal respiratory distress", yield: 6 },
    { topic: "Respiratory embryology", yield: 3 },
  ],
  "Reproductive": [
    { topic: "Pregnancy complications (ectopic, pre-eclampsia, gestational diabetes)", yield: 8 },
    { topic: "Breast pathology (fibroadenoma, DCIS, invasive carcinoma)", yield: 8 },
    { topic: "Ovarian & uterine pathology (PCOS, fibroids, endometriosis, cancers)", yield: 8 },
    { topic: "Testicular pathology (seminoma, teratoma, torsion)", yield: 7 },
    { topic: "Contraception & reproductive pharmacology", yield: 7 },
    { topic: "Menstrual cycle & hormonal regulation", yield: 7 },
    { topic: "Sexually transmitted infections", yield: 6 },
    { topic: "Prostate pathology (BPH, prostate cancer)", yield: 6 },
    { topic: "Reproductive embryology (sexual differentiation)", yield: 5 },
    { topic: "Trophoblastic disease", yield: 4 },
  ],
  "Musculoskeletal": [
    { topic: "Autoimmune joint disease (RA, SLE, gout, pseudogout)", yield: 9 },
    { topic: "Bone disorders (osteoporosis, Paget's, osteomalacia, rickets)", yield: 8 },
    { topic: "Muscle diseases (muscular dystrophies, myasthenia gravis)", yield: 7 },
    { topic: "Skin pathology (melanoma, SCC, BCC, dermatitis)", yield: 7 },
    { topic: "Bone tumors (osteosarcoma, Ewing's, giant cell)", yield: 6 },
    { topic: "Upper & lower extremity nerve injuries", yield: 6 },
    { topic: "MSK pharmacology (DMARDs, biologics, gout drugs)", yield: 6 },
    { topic: "Compartment syndrome", yield: 4 },
  ],
  "Behavioral Sciences": [
    { topic: "Ethics (autonomy, beneficence, informed consent, capacity)", yield: 9 },
    { topic: "Biostatistics (sensitivity, specificity, PPV, NPV, study types)", yield: 8 },
    { topic: "Epidemiology (incidence, prevalence, risk measures)", yield: 7 },
    { topic: "Defense mechanisms", yield: 6 },
    { topic: "Substance use disorders", yield: 6 },
    { topic: "Patient communication & HIPAA", yield: 5 },
    { topic: "Sleep stages & disorders", yield: 5 },
    { topic: "Developmental milestones", yield: 5 },
    { topic: "Grief & death/dying stages", yield: 4 },
  ],
  "Biostatistics & Epidemiology": [
    { topic: "Sensitivity, specificity, PPV, NPV", yield: 10 },
    { topic: "Study design types (RCT, cohort, case-control, cross-sectional)", yield: 9 },
    { topic: "Bias types & confounders", yield: 8 },
    { topic: "Risk measures (RR, OR, ARR, NNT)", yield: 8 },
    { topic: "Statistical tests (p-value, confidence intervals, power)", yield: 7 },
    { topic: "Screening vs diagnostic tests", yield: 7 },
    { topic: "Incidence vs prevalence", yield: 7 },
    { topic: "Lead-time & length-time bias", yield: 6 },
    { topic: "Kaplan-Meier survival curves", yield: 5 },
  ],
  "General Principles": [
    { topic: "Genetics (Mendelian, multifactorial, Hardy-Weinberg)", yield: 8 },
    { topic: "Cell biology (organelles, cytoskeleton, cell cycle)", yield: 7 },
    { topic: "Nutrition (vitamins, minerals, malnutrition)", yield: 7 },
    { topic: "Aging & geriatric changes", yield: 4 },
    { topic: "Gender differences in disease", yield: 3 },
  ],
};
